### ISSUE TITLE
Incorrect coefficient restriction

### ISSUE THREAD

**Issue by AaronFeickert** [privy-io/shamir-secret-sharing#11]
The implementation currently restricts the leading coefficient of a secret polynomial to be nonzero. The [stated goal](https://github.com/privy-io/shamir-secret-sharing/pull/2) of this appears to be avoiding a reduction in the number of shares required to reconstruct the secret. Unfortunately, this reasoning both breaks the security guarantee of the design and does not achieve the goal in a meaningful way. 

As [analyzed](https://link.springer.com/chapter/10.1007/BFb0028463) by Ghodosi _et al._ (specifically section 3.1), restricting the leading coefficient in this way allows a subthreshold of colluding players to definitively identify a value that the secret _cannot_ be, which breaks the security guarantee otherwise provided by the Shamir design.

The reason that this restriction does not meaningfully achieve its goal of protecting against a reduced-threshold condition is subtle. Suppose the intended threshold is `t` players. With no coefficient restriction, it is certainly the case that the leading coefficient will be zero with `1/256` probability. If a threshold of `t - 1` players collude and interpolate a value, they must verify that it is the correct secret; remember, they do not know in advance if the zero-coefficient case is at play. However, if the players were able to verify that the secret is correct, each player alone (without colluding) could simply try all `256` possible secrets! Therefore there is no advantage to a subthreshold of players that cannot be realized with equal expected value by non-colluding brute force.

**Comment by asta-li** [comment]
Please see the attached document with remarks on the trade-offs considered in the existing implementation and the decision to enforce non-zero leading coefficients. In summary, enforcing non-zero leading coefficients is considered to be a safer implementation choice than allowing zero leading coefficients and statistically preserves security for all instances. 

[remarks.pdf](https://github.com/privy-io/shamir-secret-sharing/files/12305161/remarks.pdf)
