### ISSUE TITLE
Having issues with importing the package in my TS file

### ISSUE THREAD

**Issue by alfheimrShiven** [privy-io/shamir-secret-sharing#16]
Here's how I'm importing the package in my `smart-wallet.ts` file
```ts
import * as shamir from "shamir-secret-sharing";
```

Error
```
TS2307: Cannot find module 'shamir-secret-sharing' or its corresponding type declarations.
```

Here are the complete logs:
```
ERROR in /Users/shiven/Documents/code/smart-wallet-client/src/smart-wallet.ts
./src/smart-wallet.ts 2:24-47
[tsl] ERROR in /Users/shiven/Documents/code/smart-wallet-client/src/smart-wallet.ts(2,25)
      TS2307: Cannot find module 'shamir-secret-sharing' or its corresponding type declarations.
ts-loader-default_e3b0c44298fc1c14

webpack 5.89.0 compiled with 2 errors in 1527 ms
```

What's causing this and how can this be resolved? Let me know if you need any additional info. Thanks!

**Comment by alfheimrShiven** [comment]
Could you include the official type declaration file for extending support to Typescript projects.

**Comment by benjreinhart** [comment]
Hey @alfheimrShiven, from the error message, it looks like the build system cannot find the module at all. Are you sure it's been installed to your project's node_modules?

The project does export the proper ts declaration files. You can see them in the [resulting NPM package here](https://www.npmjs.com/package/shamir-secret-sharing?activeTab=code).

**Comment by alfheimrShiven** [comment]
Hey @benjreinhart I'm sorry to bother you. **It's working just fine.** I was supposed to create this issue on [another repo](https://github.com/jwerle/shamirs-secret-sharing) but got confused by very similar names I guess🫣.
